//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JordanToursim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentId { get; set; }
        public int id { get; set; }
        public int TripId { get; set; }
        public string departmentName { get; set; }
        public string DepartmentImage { get; set; }
    
        public virtual City City { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
