//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JordanToursim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Partners = new HashSet<Partner>();
        }
    
        public int TripId { get; set; }
        public int Participant_ID { get; set; }
        public string ParticipantName { get; set; }
        public string Participant_National_ID { get; set; }
        public System.DateTime Participant_Birthdate { get; set; }
        public string Participant_Email { get; set; }
        public string NumberList { get; set; }
        public string Participant_Phone_No { get; set; }
        public string Participant_Image_IDcard { get; set; }
        public System.DateTime Order_Date { get; set; }
        public bool Movement_way { get; set; }
        public string City { get; set; }
        public bool isPartner { get; set; }
        public Nullable<bool> Order_Status { get; set; }
        public bool agreement { get; set; }
    
        public virtual Trip Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner> Partners { get; set; }
    }
}
