//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JordanToursim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Nullable<int> Participant_ID { get; set; }
        public int Id { get; set; }
        public string PartnerName { get; set; }
        public int PartnerNationalNumber { get; set; }
        public System.DateTime PartnerBirthDay { get; set; }
        public string PartnerIdentityImg { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
