//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JordanToursim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.Departments = new HashSet<Department>();
            this.Orders = new HashSet<Order>();
        }
    
        public int TripId { get; set; }
        public string Trip_Name { get; set; }
        public string Trip_Description { get; set; }
        public System.DateTime Trip_Date_Time_From { get; set; }
        public System.DateTime Trip_Date_Time_To { get; set; }
        public int Trip_Capacity { get; set; }
        public string City_Name { get; set; }
        public string Department_Name { get; set; }
        public double Ticket_Price { get; set; }
        public string Trip_Image_web { get; set; }
        public string Trip_Image_phone { get; set; }
        public bool IsPublished { get; set; }
        public bool BusMovement { get; set; }
        public bool Lunch { get; set; }
        public bool OvernightStay { get; set; }
        public bool TouristGuide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
